slam:
  enabled: enable
  params_file: ""

exploration:
  enabled: false
  params_file: ""

perception:
  enabled: false
  marker_size: 0.75
  aruco_dict: "DICT_6X6_1000"
  image_topic: "/oak/rgb/color"

gazebo:
  rviz: true
